name: Deploy to Azure App Service

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  TF_WORKSPACE: default
  RESOURCE_GROUP: "your-rg-name" # Match your Terraform

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Get App Service URL
        id: tf-output
        run: |
          URL=$(terraform output -raw app_service_url)
          echo "APP_URL=$URL" >> $GITHUB_ENV
          echo "::set-output name=app_url::$URL"
        working-directory: ./infra

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.tf-output.outputs.app_url }}
          package: ./movie-analyst-ui
          runtime: "NODE|14-lts"
