---
- name: Configure MySQL environment and database
  hosts: nodes  # Matches your inventory group
  become: yes
  vars:
    db_user: "applicationuser"
    db_password: "your_secure_password"  # Use Ansible Vault for security
    db_name: "movie_db"
    mysql_script_path: "ansible/files/mysql/movie_db.sql"

  tasks:
    - name: Set db_host dynamically from inventory
      set_fact:
        db_host: "{{ hostvars['mysql_server']['ansible_host'] }}"  # Assuming 'mysql_server' is your DB host in inventory

    - name: Add environment variables to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop:
        - { key: "DB_HOST", value: "{{ db_host }}" }
        - { key: "DB_USER", value: "{{ db_user }}" }
        - { key: "DB_PASS", value: "{{ db_password }}" }
        - { key: "DB_NAME", value: "{{ db_name }}" }
      no_log: true

    - name: Install MySQL client
      apt:
        name: mysql-client
        update_cache: yes
        state: present

    - name: Ensure MySQL scripts directory exists
      file:
        path: "/etc/ansible/mysql"
        state: directory
        mode: "0755"

    - name: Transfer MySQL initialization script
      copy:
        src: "{{ mysql_script_path }}"
        dest: "/etc/ansible/mysql/movie_db.sql"
        owner: root
        group: root
        mode: "0640"
      when: mysql_script_path is defined and lookup('fileglob', mysql_script_path)|length > 0

    - name: Load MySQL initialization script
      mysql_db:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        name: "{{ db_name }}"
        state: import
        target: "/etc/ansible/mysql/movie_db.sql"
      register: db_import
      no_log: true
      changed_when: "'OK' in db_import.msg"
      failed_when: >
        db_import.failed and
        ('already exists' not in db_import.msg)