---
- name: Configure MySQL environment and database
  hosts: mysql_server
  become: yes
  vars:
    db_user: "applicationuser"
    db_password: "your_secure_password"
    db_name: "movie_db"
    mysql_script_path: "ansible/files/mysql/movie_db.sql"

  tasks:
    - name: Set db_host dynamically
      set_fact:
        db_host: "{{ hostvars[groups['mysql_server'][0]]['ansible_host'] }}"

    - name: Add environment variables to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop:
        - { key: "DB_HOST", value: "{{ db_host }}" }
        - { key: "DB_USER", value: "{{ db_user }}" }
        - { key: "DB_PASS", value: "{{ db_password }}" }
        - { key: "DB_NAME", value: "{{ db_name }}" }
      no_log: true

    - name: Install MySQL client
      apt:
        name: mysql-client
        update_cache: yes
        state: present

    - name: Ensure MySQL scripts directory exists
      file:
        path: "/etc/ansible/mysql"
        state: directory
        mode: "0755"

    - name: Transfer MySQL initialization script
      copy:
        src: "{{ mysql_script_path }}"
        dest: "/etc/ansible/mysql/movie_db.sql"
        owner: root
        group: root
        mode: "0640"

    - name: Load MySQL initialization script
      shell: |
        mysql -h {{ db_host }} -u{{ db_user }} -p'{{ db_password }}' {{ db_name }} < /etc/ansible/mysql/movie_db.sql
      args:
        executable: /bin/bash
      no_log: true
      changed_when: false
