---
- name: Deploy frontend to Azure Web App
  hosts: localhost
  connection: local
  vars:
    APP_SERVICE_NAME: "{{ lookup('env', 'APP_SERVICE_NAME') }}"
    RESOURCE_GROUP_NAME: "{{ lookup('env', 'RESOURCE_GROUP_NAME') }}"
    FRONTEND_PATH: "../src/movie-analyst-ui"
    ZIP_PATH: "/tmp/frontend.zip"
    BACKEND_URL: "{{ lookup('env', 'LB_API_URL') }}"

  tasks:

    - name: Ensure frontend path exists
      stat:
        path: "{{ FRONTEND_PATH }}"
      register: frontend_dir

    - name: Fail if frontend path does not exist
      fail:
        msg: "The frontend path '{{ FRONTEND_PATH }}' does not exist."
      when: not frontend_dir.stat.exists

    - name: Create zip package (exclude node_modules and build artifacts)
      command: >
        zip -r {{ ZIP_PATH }} . -x "node_modules/*" -x ".next/*" -x "dist/*"
      args:
        chdir: "{{ FRONTEND_PATH }}"

    - name: Enable Oryx build (SCM_DO_BUILD_DURING_DEPLOYMENT=true)
      shell: |
        az webapp config appsettings set \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

    - name: Set backend API URL as environment variable
      shell: |
        az webapp config appsettings set \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --settings NEXT_PUBLIC_BACKEND_URL={{ BACKEND_URL }}

    - name: Deploy zip to Azure Web App
      shell: |
        az webapp deploy \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --src-path {{ ZIP_PATH }} \
          --type zip
