---
- name: Deploy Frontend to Azure Web App
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    frontend_project_path: "../src/movie-analyst-ui"
    zip_file: "movie-analyst-ui.zip"
    app_name: "{{ lookup('env', 'APP_SERVICE_NAME') }}"
    resource_group: "{{ lookup('env', 'RESOURCE_GROUP_NAME') }}"
    api_url: "{{ lookup('env', 'LB_API_URL') }}"

  tasks:
    - name: Ensure Azure CLI is logged in
      command: az account show
      register: azure_login
      failed_when: azure_login.rc != 0

    - name: Install dependencies
      command: npm install
      args:
        chdir: "{{ frontend_project_path }}"

    - name: Build frontend project
      command: npm run build
      args:
        chdir: "{{ frontend_project_path }}"

    - name: Archive build output
      community.general.archive:
        path: "{{ frontend_project_path }}/build"
        dest: "/tmp/{{ zip_file }}"
        format: zip

    - name: Set BACKEND_URL in App Service configuration
      command: >
        az webapp config appsettings set
        --name {{ app_name }}
        --resource-group {{ resource_group }}
        --settings BACKEND_URL={{ api_url }}

    - name: Deploy ZIP to Azure Web App
      command: >
        az webapp deployment source config-zip
        --resource-group {{ resource_group }}
        --name {{ app_name }}
        --src /tmp/{{ zip_file }}
