---
- name: Deploy Frontend to Azure Web App
  hosts: localhost
  vars:
    APP_SERVICE_NAME: "{{ lookup('env', 'APP_SERVICE_NAME') }}"
    RESOURCE_GROUP_NAME: "{{ lookup('env', 'RESOURCE_GROUP_NAME') }}"
    FRONTEND_PATH: "../src/movie-analyst-ui"
    ZIP_NAME: "frontend.zip"
    ZIP_PATH: "/tmp/{{ ZIP_NAME }}"
    BACKEND_URL: "{{ lookup('env', 'LB_API_URL') }}"

  tasks:
    - name: Ensure zip is installed
      package:
        name: zip
        state: present
      become: yes

    - name: Set BACKEND_URL in .env file (optional)
      copy:
        dest: "{{ FRONTEND_PATH }}/.env"
        content: |
          BACKEND_URL={{ BACKEND_URL }}

    - name: Create zip package for deployment
      shell: |
        cd {{ FRONTEND_PATH }}
        zip -r {{ ZIP_PATH }} . -x "node_modules/*"

    - name: Deploy zip to Azure Web App
      shell: |
        az webapp deployment source config-zip \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --src {{ ZIP_PATH }}
