---
- name: Deploy Frontend to Azure Web App
  hosts: localhost
  vars:
    frontend_project_path: "../src/movie-analyst-ui"
    zip_file: "movie-analyst-ui.zip"
    app_name: "{{ lookup('env', 'APP_SERVICE_NAME') }}"
    resource_group: "{{ lookup('env', 'RESOURCE_GROUP_NAME') }}"
    api_url: "{{ lookup('env', 'LB_API_URL') }}"

  tasks:
    - name: Ensure Azure CLI is logged in
      command: az account show
      register: azure_login
      failed_when: azure_login.rc != 0

    - name: Inject API URL into EJS templates (optional)
      lineinfile:
        path: "{{ frontend_project_path }}/views/index.ejs"
        regexp: 'const API_URL = .*'
        line: 'const API_URL = "{{ api_url }}"'
      when: api_url is defined

    - name: Install dependencies
      command: npm install
      args:
        chdir: "{{ frontend_project_path }}"

    - name: Archive frontend project
      community.general.archive:
        path: "{{ frontend_project_path }}"
        dest: "/tmp/{{ zip_file }}"
        format: zip
        exclude_path:
          - node_modules

    - name: Deploy ZIP to Azure Web App
      command: >
        az webapp deployment source config-zip
        --resource-group {{ resource_group }}
        --name {{ app_name }}
        --src /tmp/{{ zip_file }}
