---
- name: Deploy frontend to Azure Web App
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: softdevrg
    app_name: softdefault-movies-app
    frontend_path: /home/adminuser/frontend
    zip_path: /tmp/frontend.zip

  tasks:
    - name: Enable Oryx build (SCM_DO_BUILD_DURING_DEPLOYMENT=true)
      shell: |
        az webapp config appsettings set \
          --resource-group {{ resource_group }} \
          --name {{ app_name }} \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

    - name: Create zip package (exclude node_modules and build artifacts)
      shell: |
        zip -r {{ zip_path }} . -x "node_modules/*" -x ".next/*" -x "dist/*"
      args:
        chdir: "{{ frontend_path }}"

    - name: Deploy zip to Azure Web App
      shell: |
        az webapp deploy \
          --resource-group {{ resource_group }} \
          --name {{ app_name }} \
          --src-path {{ zip_path }} \
          --type zip

    - name: Show success message
      debug:
        msg: "✅ Successfully deployed to https://{{ APP_SERVICE_NAME }}.azurewebsites.net"
