---
- name: Deploy Frontend to Azure Web App
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    APP_SERVICE_NAME: "{{ lookup('env', 'APP_SERVICE_NAME') }}"
    RESOURCE_GROUP_NAME: "{{ lookup('env', 'RESOURCE_GROUP_NAME') }}"
    FRONTEND_PATH: "../src/movie-analyst-ui"
    BACKEND_URL: "{{ lookup('env', 'LB_API_URL') }}"

  tasks:
    - name: Enable Oryx build (SCM_DO_BUILD_DURING_DEPLOYMENT=true)
      shell: |
        az webapp config appsettings set \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

    - name: Set BACKEND_URL in .env file
      copy:
        dest: "{{ FRONTEND_PATH }}/.env"
        content: |
          BACKEND_URL={{ BACKEND_URL }}

    - name: Deploy app folder to Azure Web App (modern Oryx build)
      shell: |
        az webapp deploy \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --src-path "{{ FRONTEND_PATH }}" \
          --type code
