---
- name: Deploy Frontend to Azure Web App
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    APP_SERVICE_NAME: "{{ lookup('env', 'APP_SERVICE_NAME') }}"
    RESOURCE_GROUP_NAME: "{{ lookup('env', 'RESOURCE_GROUP_NAME') }}"
    FRONTEND_PATH: "../src/movie-analyst-ui"
    ZIP_NAME: "frontend.zip"
    ZIP_PATH: "/tmp/{{ ZIP_NAME }}"
    BACKEND_URL: "{{ lookup('env', 'LB_API_URL') }}"

  tasks:
    - name: Ensure zip is installed
      package:
        name: zip
        state: present
      become: yes

    - name: Set BACKEND_URL in .env file
      copy:
        dest: "{{ FRONTEND_PATH }}/.env"
        content: |
          BACKEND_URL={{ BACKEND_URL }}

    - name: Create zip package for deployment (excluding node_modules)
      shell: |
        zip -r {{ ZIP_PATH }} . -x "node_modules/*"
      args:
        chdir: "{{ FRONTEND_PATH }}"

    - name: Deploy zip to Azure Web App
      shell: |
        az webapp deployment source config-zip \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --src {{ ZIP_PATH }}

    - name: Set custom startup command for Azure Web App
      shell: |
        az webapp config set \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --startup-file "npm start"

    - name: Enable Oryx build by setting SCM_DO_BUILD_DURING_DEPLOYMENT=true
      shell: |
        az webapp config appsettings set \
          --resource-group {{ RESOURCE_GROUP_NAME }} \
          --name {{ APP_SERVICE_NAME }} \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
