---
- name: Deploy Frontend to Azure App Service
  hosts: localhost
  connection: local
  vars:
    frontend_src: "{{ frontend_src_dir | default('src/movie-analyst-ui') }}"
    node_version: "16-lts"
    
  tasks:
    # --- Debug variables first ---
    - name: Verify Azure resource variables
      debug:
        msg: |
          RESOURCE_GROUP: {{ resource_group_name }}
          APP_NAME: {{ app_service_name }}
          BACKEND_URL: {{ lb_api_url }}

    # --- Build steps ---
    - name: Install dependencies
      command: npm install
      args:
        chdir: "{{ frontend_src }}"

    - name: Zip frontend application
      archive:
        path: "{{ frontend_src }}/"
        dest: "./frontend-deploy.zip"
        format: zip
        exclude_path:
          - "node_modules/.cache/"
          - "test/"
          - ".git/"

    # --- Azure Deployment with API Version Fix ---
    - name: Get latest supported API version
      command: >
        az provider show --namespace Microsoft.Web
        --query "resourceTypes[?resourceType=='sites'].apiVersions[0]"
        --output tsv
      register: api_version_check
      changed_when: false
      ignore_errors: yes

    - name: Set actual API version
      set_fact:
        azure_api_version: >-
          {% if api_version_check is succeeded %}
            {{ api_version_check.stdout }}
          {% else %}
            2024-11-01  # Fallback version
          {% endif %}

    - name: Update Node.js runtime
      command: >
        az webapp config set
        --resource-group "{{ resource_group_name }}"
        --name "{{ app_service_name }}"
        --linux-fx-version "NODE|{{ node_version }}"
        --output none
      environment:
        AZURE_CLI_DEFAULT_API_VERSION: "{{ azure_api_version }}"

    - name: Set app settings
      command: >
        az webapp config appsettings set
        --resource-group "{{ resource_group_name }}"
        --name "{{ app_service_name }}"
        --settings >-
          NODE_ENV=production
          WEBSITES_PORT=3000
          BACKEND_URL="{{ lb_api_url }}:8080"
          WEBSITES_ENABLE_APP_SERVICE_STORAGE=true
        --output none
      environment:
        AZURE_CLI_DEFAULT_API_VERSION: "{{ azure_api_version }}"

    - name: Deploy ZIP package
      command: >
        az webapp deployment source config-zip
        --resource-group "{{ resource_group_name }}"
        --name "{{ app_service_name }}"
        --src "./frontend-deploy.zip"
        --output none
      environment:
        AZURE_CLI_DEFAULT_API_VERSION: "{{ azure_api_version }}"

    # --- Verification ---
    - name: Verify deployment
      uri:
        url: "https://{{ app_service_name }}.azurewebsites.net"
        return_content: yes
        status_code: 200
      register: deployment_check
      retries: 5
      delay: 30
      until: deployment_check.status == 200
      ignore_errors: yes

    - name: Show deployment result
      debug:
        msg: "✅ Successfully deployed to https://{{ app_service_name }}.azurewebsites.net"
      when: deployment_check.status == 200