---
- name: Configure infrastructure
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure all nodes are in /etc/hosts
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_host | default(item) }} {{ item }}"
        state: present
      loop: "{{ groups['all'] }}"

- name: Configure control node ssh
  hosts: control
  gather_facts: false
  vars:
    ssh_private_key_path: "/home/adminuser/.ssh/vm_ssh_key"
  tasks:
    - name: Create ~/.ssh directory
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: "0700"

    - name: Copy SSH private key to ~/.ssh/vm_ssh_key
      ansible.builtin.copy:
        src: "{{ ssh_private_key_path }}"
        dest: "{{ ssh_private_key_path }}"
        mode: "0600"
        remote_src: yes  # La clave ya está en la jumphost

    - name: Update SSH config for node* hosts
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        block: |
          Host node*
            User adminuser
            IdentityFile {{ ssh_private_key_path }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NODE CONFIG"
        create: yes
